### ISSUE TITLE
Adjust image quality settings for best network throughput

### ISSUE THREAD

**Issue by loreV** [loreV/SeC#129]
Given 4 image quality settings, namely `xl`, `l`, `m`, `h` (extra low, low, medium, high quality), an uploaded image shall be compressed by the job as it follows:
- 3 mb
  - `h` : >= 3mb (used for further compression)
  - `m` : >= 1.5mb 
  - `l` : >= 500kb
  - `xl`: >= 250kb

ℹ️ Resolution can be adjusted to match the required size.

**Comment by marcofranzoni** [comment]
@loreV I would resize low and extra low quality by some amount (e.g 50% and 75% maintaining the aspect ratio), because decreasing only the `compressionQuality` parameter yields to very poor images. What do you think?

**Comment by loreV** [comment]
Agreed!
