### ISSUE TITLE
Add indexes to DB

### ISSUE THREAD

**Issue by loreV** [loreV/SeC#21]
# Acceptance criteria
- Improve DB performance by adding DB indexes based on the possible request that can be received.
- Indexes shall be added to DB conf at application startup time

# Notes for testing
- Shall verify the calls use the indexes

**Comment by SaraGiuliaM** [comment]
**DB index proposal:**
- **Trail Name** (targeted also by requests correlated to Accessibility Notification)
- **Place ID** (a variety of trails could meet the same Place ID. A single Place ID could have many different names)
- **POI ID** (targeted also by requests correlated to Trail Code and POI macro-types)

**Comment by loreV** [comment]
Moving this to v1.0, as not needed for vCT
