### ISSUE TITLE
Set up a test for the RectangleValidator 

### ISSUE THREAD

**Issue by SaraGiuliaM** [loreV/SeC#72]
Check that an oversized rectangle (diagonal > 150 km) will be considered as non-valid input for fetching intersecting trails

**Comment by loreV** [comment]
As we discussed, let's switch from 150km allowed diagonal size to 50km allowed diagonal size, in order to preserve resources and avoid useless computation.

**Comment by loreV** [comment]
@SaraGiuliaM shall we close this?
