### ISSUE TITLE
Decrease resolution at higher flight altitude

### ISSUE THREAD

**Issue by SaraGiuliaM** [loreV/SeC#76]
The aim is to decrease resolution of displayed trails at higher flight altitude over the map (users will discover the **full set of available GPX data-points only when zooming in**).
Practically, we are going to trim trackpoints according to the value of a certain variable.

To begin with, we could set the scale on  the **“zoom level” variable value**, which is  contained in the frontend library Leaflet (https://leafletjs.com/examples/zoom-levels/).
As a next step, we could rely on the **bottomleft & topright view vertexes** in order to determine the actual view diagonal length and the due trimming.

In order to reduce the number of trackpoints while maintaining the overall shape of the curve we could use the following  java implementation of the **Ramer–Douglas–Peucker algorithm** (https://github.com/LukaszWiktor/series-reducer).

**Question**: while the track simplification algorithm is working for us, wouldn’t be a good idea to draw on the map only the points and not the point-connecting line? In my opinion, this scenario would give a better idea of ‘route with reduced number of data points’.

**Comment by loreV** [comment]
Hi @SaraGiuliaM. To respond to your question: I get your point. I think we shall talk about this with our designer and frontend devs. Let's postpone this discussion for a later time.

**Comment by SaraGiuliaM** [comment]
In order to save time and computation effort, we are going to **pre-compute** three track global 'pictures' at increasing lower resolution.
Level of resolution will be linked to precise “**zoom level**” variable value (see frontend library Leaflet, map.setZoom(x)):
 “zoom level”  value of 9  -> super-low HD
... 10 -> low HD
... 11 -> medium HD
... 12  -> full HD


**Focussing on**:

- TrailDto (Dto: data structure we pass on from BE to FE) -> PlaceRefDto startLocation, PlaceRefDto endLocation, List<PlaceRefDto> locations, List<TrailCoordinatesDto> coordinates
- TrailIntersectionDto -> List<CoordinatesDto> points

We will simplify tracks by means of the Ramer–Douglas–Peucker algorithm. Track points that should always be included (no matter how low track resolution we would like to achieve): startLocation, endLocation, locations, points (<<<< OK?)
Therefore, we will simplify based on the "coordinates" pool (<<<< OK? Or we have to subtract "startLocation", "endLocation", "locations", "points"  from "coordinates" ?)

**From https://github.com/LukaszWiktor/series-reducer:**
List<Point> reduced = SeriesReducer.reduce(points, epsilon);
P.S. points: pool available for simplification; epsilon defines a margin within which points can be removed (e.g. 0.01)

**Comment by loreV** [comment]
> In order to save time and computation effort, we are going to **pre-compute** three track global 'pictures' at increasing lower resolution.
> Level of resolution will be linked to precise “**zoom level**” variable value (see frontend library Leaflet, map.setZoom(x)):
> “zoom level” value of 9 -> super-low HD
> ... 10 -> low HD
> ... 11 -> medium HD
> ... 12 -> full HD
> 
> **Focussing on**:
> 
>     * TrailDto (Dto: data structure we pass on from BE to FE) -> PlaceRefDto startLocation, PlaceRefDto endLocation, List locations, List coordinates
> 
>     * TrailIntersectionDto -> List points
> 
> 
> We will simplify tracks by means of the Ramer–Douglas–Peucker algorithm. Track points that should always be included (no matter how low track resolution we would like to achieve): startLocation, endLocation, locations, points (<<<< OK?)
> Therefore, we will simplify based on the "coordinates" pool (<<<< OK? Or we have to subtract "startLocation", "endLocation", "locations", "points" from "coordinates" ?)
> 
> **From https://github.com/LukaszWiktor/series-reducer:**
> List reduced = SeriesReducer.reduce(points, epsilon);
> P.S. points: pool available for simplification; epsilon defines a margin within which points can be removed (e.g. 0.01)

Hi @SaraGiuliaM! All the above is correct. To answer the open points:
- `Coordinates` is the correct pool the the "FULL HD" track 
- `Coordinates` includes start and endlocation
**I believe that, as for v1.0, it does not matter that low-HD, medium-HD contain also the intersections and locations**_, though it would be nice to have them._

**Comment by loreV** [comment]
(Due date: 31 May 2021)

**Comment by loreV** [comment]
https://stackoverflow.com/questions/34010298/simplify-java-by-hgoebl-issue-with-reduced-points-list-always-size-2

**Comment by SaraGiuliaM** [comment]
**Recap:**
1. implementation of the reduction algorithm (importing the package Simplify-Java by hgoebl, https://github.com/hgoebl/simplify-java). Note that we needed to convert our lists to arrays and to convert Lat/Lon by multiplying with 1e6 (see https://stackoverflow.com/questions/34010298/simplify-java-by-hgoebl-issue-with-reduced-points-list-always-size-2).
2. no reduction obtained when inputting the small datasets within the TrailSimplifierTest. The algorithm is working when importing a real GPS track (for the moment we have just a quantitative judgment on the number of points).
3. added Java enums in If-statements for choosing a clearer tolerance value during the simplification
